//! macOS `NativeClipboard`: changeCount polling on one thread, concealed-type filtering, host-only writes.

use std::ptr::NonNull;
use std::sync::{Arc, Condvar, Mutex, PoisonError};
use std::task::{Wake, Waker};
use std::time::Duration;

use monhop_protocol::clipboard::image_within_caps;
use objc2::rc::{Retained, autoreleasepool};
use objc2::runtime::{NSObjectProtocol, ProtocolObject};
use objc2::sel;
use objc2_app_kit::{
    NSBitmapImageFileType, NSBitmapImageRep, NSPasteboard, NSPasteboardAccessBehavior,
    NSPasteboardContentsOptions, NSPasteboardItem, NSPasteboardWriting,
};
use objc2_foundation::{NSArray, NSData, NSDictionary, NSInteger, NSString};

use super::content::{self, Pick, SourceMarker};
use super::image::Rgba;
use super::native::{
    Access, Content, NativeClipboard, NativeError, Origin, ReadLimits, Skip, Snapshot,
};

const MARKER_TYPE: &str = "com.monhop.clipboard-source";
const TEXT_TYPE: &str = "public.utf8-plain-text";
const PNG_TYPE: &str = "public.png";
const TIFF_TYPE: &str = "public.tiff";
/// Types that password managers and clipboard utilities add so clipboard monitors skip the item.
const CONCEALED_TYPES: [&str; 5] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
];
/// A Finder file copy also carries the file's icon as TIFF, which must never go out.
const FILE_TYPES: [&str; 2] = ["public.file-url", "NSFilenamesPboardType"];

pub struct MacClipboard {
    pasteboard: Retained<NSPasteboard>,
    signal: Arc<Signal>,
}

impl MacClipboard {
    /// Tests use private pasteboards only: the general one is the user's real clipboard.
    #[cfg_attr(test, allow(dead_code))]
    pub fn new() -> Self {
        autoreleasepool(|_| Self::with_pasteboard(NSPasteboard::generalPasteboard()))
    }

    fn with_pasteboard(pasteboard: Retained<NSPasteboard>) -> Self {
        Self {
            pasteboard,
            signal: Arc::default(),
        }
    }

    fn change_count(&self) -> u64 {
        // Reinterpreting the bits keeps distinct counts distinct, which is all a marker needs.
        self.pasteboard.changeCount() as u64
    }

    fn read_snapshot(&self, limits: &ReadLimits) -> Result<Snapshot, NativeError> {
        let before = self.change_count();
        let types: Vec<String> = self.pasteboard.types().map_or_else(Vec::new, |types| {
            types.to_vec().iter().map(|name| name.to_string()).collect()
        });
        let (origin, content) = match classify(&types) {
            Plan::Marker => (Origin::MonHop(self.source_marker()), Content::Empty),
            Plan::Skip(skip) => (Origin::Local, Content::Skipped(skip)),
            Plan::Read(flavors) => (Origin::Local, self.read_content(flavors, limits)?),
            Plan::Empty => (Origin::Local, Content::Empty),
        };
        let after = self.change_count();
        Ok(Snapshot {
            before,
            after,
            origin,
            content,
        })
    }

    /// Copies only the bytes `SourceMarker::parse` reads, however large the stored value is.
    fn source_marker(&self) -> Option<SourceMarker> {
        let data = self
            .pasteboard
            .dataForType(&NSString::from_str(MARKER_TYPE))?;
        let mut bytes = [0_u8; SourceMarker::LEN];
        if data.len() < bytes.len() {
            return None;
        }
        // SAFETY: `bytes` has room for the `bytes.len()` bytes copied; `data` holds as many.
        unsafe { data.getBytes_length(NonNull::from(&mut bytes).cast(), bytes.len()) };
        SourceMarker::parse(&bytes)
    }

    fn read_content(&self, flavors: Flavors, limits: &ReadLimits) -> Result<Content, NativeError> {
        let text = if flavors.text {
            let data = self.data(TEXT_TYPE)?;
            if data.len() > limits.text_bytes {
                return Ok(Content::Skipped(Skip::TooLarge));
            }
            let Ok(text) = String::from_utf8(data.to_vec()) else {
                return Ok(Content::Skipped(Skip::Unsupported));
            };
            Some(text)
        } else {
            None
        };
        match (
            content::pick(text.as_deref(), flavors.png || flavors.tiff),
            text,
        ) {
            (Pick::Text, Some(text)) => Ok(Content::Text(text)),
            (Pick::Image, _) if flavors.png => self.read_png(limits),
            (Pick::Image, _) => self.read_tiff(limits),
            _ => Ok(Content::Empty),
        }
    }

    fn read_png(&self, limits: &ReadLimits) -> Result<Content, NativeError> {
        let png = self.data(PNG_TYPE)?;
        if png.len() > limits.png_bytes {
            return Ok(Content::Skipped(Skip::TooLarge));
        }
        Ok(Content::Png(png.to_vec()))
    }

    /// A TIFF is raw pixels like a DIB; the pixel caps are checked before AppKit decodes it.
    fn read_tiff(&self, limits: &ReadLimits) -> Result<Content, NativeError> {
        let tiff = self.data(TIFF_TYPE)?;
        if tiff.len() > limits.dib_bytes {
            return Ok(Content::Skipped(Skip::TooLarge));
        }
        let Some(bitmap) = NSBitmapImageRep::imageRepWithData(&tiff) else {
            return Ok(Content::Skipped(Skip::Unsupported));
        };
        if let Err(skip) = check_pixels(bitmap.pixelsWide(), bitmap.pixelsHigh()) {
            return Ok(Content::Skipped(skip));
        }
        // SAFETY: an empty properties dictionary holds no value of the wrong type.
        let png = unsafe {
            bitmap.representationUsingType_properties(
                NSBitmapImageFileType::PNG,
                &NSDictionary::new(),
            )
        };
        Ok(match png {
            None => Content::Skipped(Skip::Unsupported),
            Some(png) if png.len() > limits.png_bytes => Content::Skipped(Skip::TooLarge),
            Some(png) => Content::Png(png.to_vec()),
        })
    }

    /// A listed type whose data is missing means its owner failed to provide it.
    fn data(&self, pasteboard_type: &str) -> Result<Retained<NSData>, NativeError> {
        self.pasteboard
            .dataForType(&NSString::from_str(pasteboard_type))
            .ok_or(NativeError::Failed)
    }

    /// Content and marker land in one item and one write; `CurrentHostOnly` keeps received content
    /// out of Universal Clipboard. The item is built first so a failure leaves the clipboard alone,
    /// and the marker check sits right before the write to keep the race with a local copy short.
    fn write_item(
        &self,
        content_type: &str,
        content: &[u8],
        marker: SourceMarker,
        expected: u64,
    ) -> Result<u64, NativeError> {
        autoreleasepool(|_| {
            let item = NSPasteboardItem::new();
            let filled = item.setData_forType(
                &NSData::with_bytes(content),
                &NSString::from_str(content_type),
            ) && item.setData_forType(
                &NSData::with_bytes(&marker.to_bytes()),
                &NSString::from_str(MARKER_TYPE),
            );
            if !filled {
                return Err(NativeError::Failed);
            }
            let items = NSArray::from_retained_slice(&[
                ProtocolObject::<dyn NSPasteboardWriting>::from_retained(item),
            ]);
            if self.change_count() != expected {
                return Err(NativeError::Changed);
            }
            self.pasteboard
                .prepareForNewContentsWithOptions(NSPasteboardContentsOptions::CurrentHostOnly);
            if !self.pasteboard.writeObjects(&items) {
                return Err(NativeError::Failed);
            }
            Ok(self.change_count())
        })
    }
}

impl NativeClipboard for MacClipboard {
    fn change_marker(&self) -> u64 {
        autoreleasepool(|_| self.change_count())
    }

    fn wait(&mut self, timeout: Duration) {
        self.signal.wait(timeout);
    }

    fn waker(&self) -> Waker {
        Waker::from(Arc::clone(&self.signal))
    }

    fn access(&self) -> Access {
        autoreleasepool(|_| {
            // Paste privacy and `accessBehavior` arrived in macOS 15.4.
            if !self.pasteboard.respondsToSelector(sel!(accessBehavior)) {
                return Access::Allowed;
            }
            access_from(self.pasteboard.accessBehavior())
        })
    }

    fn read(&mut self, limits: &ReadLimits) -> Result<Snapshot, NativeError> {
        autoreleasepool(|_| self.read_snapshot(limits))
    }

    fn write_text(
        &mut self,
        text: &str,
        marker: SourceMarker,
        expected: u64,
    ) -> Result<u64, NativeError> {
        self.write_item(TEXT_TYPE, text.as_bytes(), marker, expected)
    }

    fn write_png(
        &mut self,
        png: &[u8],
        _rgba: Option<&Rgba>,
        marker: SourceMarker,
        expected: u64,
    ) -> Result<u64, NativeError> {
        self.write_item(PNG_TYPE, png, marker, expected)
    }
}

fn access_from(behavior: NSPasteboardAccessBehavior) -> Access {
    match behavior {
        NSPasteboardAccessBehavior::AlwaysAllow => Access::Allowed,
        NSPasteboardAccessBehavior::Ask => Access::Ask,
        NSPasteboardAccessBehavior::AlwaysDeny => Access::Denied,
        // `Default`: no access alert has been shown yet, so System Settings does not list the app.
        _ => Access::Unknown,
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct Flavors {
    text: bool,
    png: bool,
    tiff: bool,
}

/// What `read` may touch, decided from the type list alone.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Plan {
    /// MonHop wrote it: only the marker is read.
    Marker,
    Skip(Skip),
    Read(Flavors),
    Empty,
}

fn classify<S: AsRef<str>>(types: &[S]) -> Plan {
    let has = |wanted: &str| types.iter().any(|name| name.as_ref() == wanted);
    if has(MARKER_TYPE) {
        return Plan::Marker;
    }
    if CONCEALED_TYPES.into_iter().any(has) {
        return Plan::Skip(Skip::Concealed);
    }
    if FILE_TYPES.into_iter().any(has) {
        return Plan::Skip(Skip::Files);
    }
    let flavors = Flavors {
        text: has(TEXT_TYPE),
        png: has(PNG_TYPE),
        tiff: has(TIFF_TYPE),
    };
    if flavors.text || flavors.png || flavors.tiff {
        Plan::Read(flavors)
    } else {
        Plan::Empty
    }
}

fn check_pixels(width: NSInteger, height: NSInteger) -> Result<(), Skip> {
    if width <= 0 || height <= 0 {
        return Err(Skip::Unsupported);
    }
    match (u32::try_from(width), u32::try_from(height)) {
        (Ok(width), Ok(height)) if image_within_caps(width, height) => Ok(()),
        _ => Err(Skip::TooLarge),
    }
}

/// Cuts `wait` short from any thread; a wake that lands first ends the next wait at once.
#[derive(Default)]
struct Signal {
    woken: Mutex<bool>,
    condvar: Condvar,
}

impl Signal {
    fn wait(&self, timeout: Duration) {
        let woken = self.woken.lock().unwrap_or_else(PoisonError::into_inner);
        let (mut woken, _) = self
            .condvar
            .wait_timeout_while(woken, timeout, |woken| !*woken)
            .unwrap_or_else(PoisonError::into_inner);
        *woken = false;
    }
}

impl Wake for Signal {
    fn wake(self: Arc<Self>) {
        self.wake_by_ref();
    }

    fn wake_by_ref(self: &Arc<Self>) {
        *self.woken.lock().unwrap_or_else(PoisonError::into_inner) = true;
        self.condvar.notify_all();
    }
}

#[cfg(test)]
mod tests {
    use std::ops::{Deref, DerefMut};
    use std::thread;
    use std::time::Instant;

    use monhop_protocol::clipboard::{MAX_CLIPBOARD_PNG, MAX_CLIPBOARD_SIDE, png_dimensions};
    use objc2::msg_send;

    use super::*;
    use crate::clipboard::image::encode_png;

    #[test]
    fn the_monhop_marker_wins_over_every_other_type() {
        let types = [
            "public.utf8-plain-text",
            "org.nspasteboard.ConcealedType",
            "public.file-url",
            "public.png",
            "com.monhop.clipboard-source",
        ];
        assert_eq!(classify(&types), Plan::Marker);
    }

    #[test]
    fn concealed_items_are_skipped_before_files_or_content() {
        for concealed in [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
            "de.petermaurer.TransientPasteboardType",
        ] {
            let types = ["public.utf8-plain-text", "public.file-url", concealed];
            assert_eq!(classify(&types), Plan::Skip(Skip::Concealed), "{concealed}");
        }
    }

    #[test]
    fn file_copies_are_skipped_despite_their_icon() {
        for files in ["public.file-url", "NSFilenamesPboardType"] {
            let types = [files, "public.tiff", "public.utf8-plain-text"];
            assert_eq!(classify(&types), Plan::Skip(Skip::Files), "{files}");
        }
    }

    #[test]
    fn content_types_decide_what_is_read() {
        let read = |text, png, tiff| Plan::Read(Flavors { text, png, tiff });
        assert_eq!(
            classify(&["public.utf8-plain-text"]),
            read(true, false, false)
        );
        assert_eq!(classify(&["public.png"]), read(false, true, false));
        assert_eq!(classify(&["public.tiff"]), read(false, false, true));
        assert_eq!(
            classify(&["public.png", "public.html", "public.utf8-plain-text"]),
            read(true, true, false)
        );
        assert_eq!(
            classify(&["public.html", "com.apple.flat-rtfd"]),
            Plan::Empty
        );
        assert_eq!(classify::<&str>(&[]), Plan::Empty);
    }

    #[test]
    fn access_behavior_maps_to_access() {
        let cases = [
            (NSPasteboardAccessBehavior::AlwaysAllow, Access::Allowed),
            (NSPasteboardAccessBehavior::Ask, Access::Ask),
            (NSPasteboardAccessBehavior::AlwaysDeny, Access::Denied),
            (NSPasteboardAccessBehavior::Default, Access::Unknown),
            (NSPasteboardAccessBehavior(7), Access::Unknown),
        ];
        for (behavior, access) in cases {
            assert_eq!(access_from(behavior), access, "{behavior:?}");
        }
    }

    #[test]
    fn tiff_pixel_sizes_are_checked_against_the_caps() {
        let side = NSInteger::try_from(MAX_CLIPBOARD_SIDE).unwrap();
        assert_eq!(check_pixels(1, 1), Ok(()));
        assert_eq!(check_pixels(8_000, 8_000), Ok(()));
        assert_eq!(check_pixels(side, 1), Ok(()));
        assert_eq!(check_pixels(0, 5), Err(Skip::Unsupported));
        assert_eq!(check_pixels(5, -1), Err(Skip::Unsupported));
        assert_eq!(check_pixels(side + 1, 1), Err(Skip::TooLarge));
        assert_eq!(check_pixels(1, side + 1), Err(Skip::TooLarge));
        assert_eq!(check_pixels(8_001, 8_000), Err(Skip::TooLarge));
    }

    #[test]
    fn a_wake_ends_the_wait_and_an_early_wake_ends_only_the_next_one() {
        let signal = Arc::new(Signal::default());
        let waker = Waker::from(Arc::clone(&signal));

        waker.wake_by_ref();
        let started = Instant::now();
        signal.wait(Duration::from_secs(30));
        assert!(started.elapsed() < Duration::from_secs(10));

        let started = Instant::now();
        signal.wait(Duration::from_millis(50));
        assert!(started.elapsed() >= Duration::from_millis(50));

        let remote = waker.clone();
        let waking = thread::spawn(move || {
            thread::sleep(Duration::from_millis(50));
            remote.wake();
        });
        let started = Instant::now();
        signal.wait(Duration::from_secs(30));
        assert!(started.elapsed() < Duration::from_secs(10));
        waking.join().unwrap();
    }

    /// A private pasteboard, removed from the pasteboard server when the test ends.
    struct Scratch(MacClipboard);

    impl Scratch {
        fn new() -> Self {
            Self(MacClipboard::with_pasteboard(
                NSPasteboard::pasteboardWithUniqueName(),
            ))
        }

        /// A local copy by another app: raw data, no marker.
        fn copy(&self, items: &[(&str, &[u8])]) {
            autoreleasepool(|_| {
                self.0.pasteboard.clearContents();
                for (pasteboard_type, bytes) in items {
                    let data = NSData::with_bytes(bytes);
                    let name = NSString::from_str(pasteboard_type);
                    assert!(self.0.pasteboard.setData_forType(Some(&data), &name));
                }
            });
        }

        fn string(&self, pasteboard_type: &str) -> Option<String> {
            autoreleasepool(|_| {
                let name = NSString::from_str(pasteboard_type);
                self.0
                    .pasteboard
                    .stringForType(&name)
                    .map(|text| text.to_string())
            })
        }
    }

    impl Deref for Scratch {
        type Target = MacClipboard;

        fn deref(&self) -> &MacClipboard {
            &self.0
        }
    }

    impl DerefMut for Scratch {
        fn deref_mut(&mut self) -> &mut MacClipboard {
            &mut self.0
        }
    }

    impl Drop for Scratch {
        fn drop(&mut self) {
            // SAFETY: releaseGlobally takes no arguments and returns nothing.
            let () = unsafe { msg_send![&*self.0.pasteboard, releaseGlobally] };
        }
    }

    fn marker(write: u64) -> SourceMarker {
        SourceMarker {
            token: 0x1234_5678_9abc_def0,
            write,
        }
    }

    fn png(width: u32, height: u32) -> Vec<u8> {
        let pixels = (0..width * height)
            .flat_map(|index| [index as u8, 40, 200, 255])
            .collect();
        let image = Rgba::new(width, height, pixels).unwrap();
        encode_png(&image, MAX_CLIPBOARD_PNG as usize).unwrap()
    }

    fn tiff_of(png: &[u8]) -> Vec<u8> {
        autoreleasepool(|_| {
            let bitmap = NSBitmapImageRep::imageRepWithData(&NSData::with_bytes(png)).unwrap();
            bitmap.TIFFRepresentation().unwrap().to_vec()
        })
    }

    fn read(scratch: &mut Scratch, limits: &ReadLimits) -> Snapshot {
        let snapshot = scratch.read(limits).unwrap();
        assert_eq!(snapshot.before, snapshot.after);
        snapshot
    }

    #[test]
    #[ignore = "touches a native pasteboard"]
    fn received_text_pastes_and_reads_back_as_monhop_only() {
        let mut scratch = Scratch::new();
        let approved = scratch.change_marker();
        let after = scratch
            .write_text("from a peer\n", marker(1), approved)
            .unwrap();
        assert_eq!(after, scratch.change_marker());
        assert_eq!(scratch.string(TEXT_TYPE).as_deref(), Some("from a peer\n"));

        let snapshot = read(&mut scratch, &ReadLimits::STANDARD);
        assert_eq!(snapshot.after, after);
        assert_eq!(snapshot.origin, Origin::MonHop(Some(marker(1))));
        assert!(matches!(snapshot.content, Content::Empty));
    }

    #[test]
    #[ignore = "touches a native pasteboard"]
    fn a_local_text_copy_reads_as_local_text() {
        let mut scratch = Scratch::new();
        scratch.copy(&[(TEXT_TYPE, "héllo\r\nworld".as_bytes())]);
        let snapshot = read(&mut scratch, &ReadLimits::STANDARD);
        assert_eq!(snapshot.origin, Origin::Local);
        assert!(matches!(snapshot.content, Content::Text(ref text) if text == "héllo\r\nworld"));
    }

    #[test]
    #[ignore = "touches a native pasteboard"]
    fn concealed_text_is_skipped() {
        let mut scratch = Scratch::new();
        scratch.copy(&[
            (TEXT_TYPE, b"hunter2"),
            ("org.nspasteboard.ConcealedType", b""),
        ]);
        let snapshot = read(&mut scratch, &ReadLimits::STANDARD);
        assert_eq!(snapshot.origin, Origin::Local);
        assert!(matches!(
            snapshot.content,
            Content::Skipped(Skip::Concealed)
        ));
    }

    #[test]
    #[ignore = "touches a native pasteboard"]
    fn a_file_copy_is_skipped() {
        let mut scratch = Scratch::new();
        let icon = tiff_of(&png(2, 2));
        scratch.copy(&[
            ("public.file-url", b"file:///tmp/report.pdf"),
            (TIFF_TYPE, &icon),
        ]);
        let snapshot = read(&mut scratch, &ReadLimits::STANDARD);
        assert!(matches!(snapshot.content, Content::Skipped(Skip::Files)));
    }

    #[test]
    #[ignore = "touches a native pasteboard"]
    fn a_png_goes_out_byte_for_byte() {
        let mut scratch = Scratch::new();
        let image = png(3, 2);
        scratch.copy(&[(PNG_TYPE, &image)]);
        let snapshot = read(&mut scratch, &ReadLimits::STANDARD);
        assert!(matches!(snapshot.content, Content::Png(ref png) if *png == image));
    }

    #[test]
    #[ignore = "touches a native pasteboard"]
    fn a_tiff_becomes_a_png_of_the_same_size() {
        let mut scratch = Scratch::new();
        scratch.copy(&[(TIFF_TYPE, &tiff_of(&png(3, 2)))]);
        let snapshot = read(&mut scratch, &ReadLimits::STANDARD);
        let Content::Png(png) = snapshot.content else {
            panic!("expected a PNG, got {:?}", snapshot.content);
        };
        assert_eq!(png_dimensions(&png), Ok((3, 2)));
    }

    #[test]
    #[ignore = "touches a native pasteboard"]
    fn a_lone_url_beside_an_image_goes_out_as_the_image() {
        let mut scratch = Scratch::new();
        let image = png(1, 1);
        scratch.copy(&[
            (TEXT_TYPE, b"https://example.com/cat.png"),
            (PNG_TYPE, &image),
        ]);
        let snapshot = read(&mut scratch, &ReadLimits::STANDARD);
        assert!(matches!(snapshot.content, Content::Png(ref png) if *png == image));
    }

    #[test]
    #[ignore = "touches a native pasteboard"]
    fn oversized_or_invalid_text_is_skipped() {
        let mut scratch = Scratch::new();
        scratch.copy(&[(TEXT_TYPE, b"hello")]);
        let tiny = ReadLimits {
            text_bytes: 4,
            ..ReadLimits::STANDARD
        };
        let snapshot = read(&mut scratch, &tiny);
        assert!(matches!(snapshot.content, Content::Skipped(Skip::TooLarge)));

        scratch.copy(&[(TEXT_TYPE, &[0x66, 0xff, 0xfe])]);
        let snapshot = read(&mut scratch, &ReadLimits::STANDARD);
        assert!(matches!(
            snapshot.content,
            Content::Skipped(Skip::Unsupported)
        ));
    }

    #[test]
    #[ignore = "touches a native pasteboard"]
    fn every_write_moves_the_change_marker() {
        let mut scratch = Scratch::new();
        let start = scratch.change_marker();
        let text = scratch.write_text("one", marker(1), start).unwrap();
        assert!(text > start);
        let image = png(2, 1);
        let written = scratch.write_png(&image, None, marker(2), text).unwrap();
        assert!(written > text);
        assert_eq!(written, scratch.change_marker());

        let snapshot = read(&mut scratch, &ReadLimits::STANDARD);
        assert_eq!(snapshot.origin, Origin::MonHop(Some(marker(2))));
        scratch.copy(&[(TEXT_TYPE, b"local")]);
        assert!(scratch.change_marker() > written);
    }

    #[test]
    #[ignore = "touches a native pasteboard"]
    fn a_copy_after_approval_is_never_overwritten() {
        let mut scratch = Scratch::new();
        let approved = scratch.change_marker();
        scratch.copy(&[(TEXT_TYPE, b"copied just now")]);
        let copied = scratch.change_marker();
        assert_eq!(
            scratch.write_text("from a peer", marker(1), approved),
            Err(NativeError::Changed)
        );
        assert_eq!(
            scratch.write_png(&png(1, 1), None, marker(2), approved),
            Err(NativeError::Changed)
        );
        assert_eq!(scratch.change_marker(), copied);
        assert_eq!(
            scratch.string(TEXT_TYPE).as_deref(),
            Some("copied just now")
        );
    }

    #[test]
    #[ignore = "touches a native pasteboard"]
    fn a_private_pasteboard_allows_access() {
        let scratch = Scratch::new();
        assert_eq!(scratch.access(), Access::Allowed);
    }
}
