[package]
name = "monhop-platform-windows"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
autoexamples = false

[[example]]
name = "windows_native_window"
path = "examples/native_window.rs"
test = true

[dependencies]
monhop-core = { path = "../monhop-core", version = "=0.2.1" }
log = "=0.4.34"

[target.'cfg(windows)'.dependencies]
zeroize = "=1.9.0"
tokio = { version = "=1.53.1", default-features = false, features = ["net"] }
windows-sys = { version = "=0.61.2", features = ["Win32_Foundation", "Win32_Devices_Display", "Win32_Graphics_Gdi", "Win32_System_LibraryLoader", "Win32_System_Registry", "Win32_UI_Input", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging", "Win32_UI_HiDpi", "Win32_NetworkManagement_IpHelper", "Win32_NetworkManagement_Ndis", "Win32_NetworkManagement_QoS", "Win32_NetworkManagement_WiFi", "Win32_Networking_WinSock", "Win32_Security_Cryptography", "Win32_System_Memory", "Win32_System_IO", "Win32_System_Com", "Win32_Storage_FileSystem", "Win32_UI_Shell", "Win32_UI_Shell_Common", "Win32_System_StationsAndDesktops", "Win32_System_Threading", "Win32_System_Power"] }

[dev-dependencies]
tokio = { version = "=1.53.1", default-features = false, features = ["rt", "net", "time", "sync"] }

[lints]
workspace = true
